### ISSUE TITLE
Docker architecture

### ISSUE THREAD

**Issue by alpharde** [djangopbx/djangopbx#14]
I'm going to give a shot at creating docker containers for DjangoPBX and would like to know if it interacts somehow with freeswitch through the filesystem (e.g. generating xml files for configuration, etc).

**Comment by AdrianFretwell** [comment]
The normal running configuration is delivered dynamically by the XML handler on ports 8008 and 8009.  There are two XML files that are written to the filing system ~/freeswitch/vars.xml and ~/freeswitch/autoload_configs/modules.conf.xml.  There tow files are unlikely to change very often in a running system.

I have also been doing  some work with an SFTP connection layer using the paramiko library, this is to allow Django-PBX to fetch/put files on a remote freeswitch instance.

Much of this ties in with the support I am writing for clustering arrangements.  Where one DjangoPBX will mangage multiple FreeSWITCHes.  I'm hoping to have a working model in a few weeks time.  Much of it is already working with the AMQP messaging, but there are a few things to sort out like remote firewall configuration.
