### ISSUE TITLE
NO records

### ISSUE THREAD

**Issue by mrtian** [djangopbx/djangopbx#17]
I see you set pbx_call_recording_url to http://127.0.0.1:8008. But i can't find request  log in general.log  and find records not created. And I set record_session in dialplan、internal profile but it not effectived.

**Comment by AdrianFretwell** [comment]
This is a feature we are currently working on to get recordings off the FreeSWITCH box when DjangoPBX is deployed as a cluster.  I.E. One DjangoPBX, many FreeSWITCHs.

By default call recordings will be stored in ~/media/fs/recordings/<domain>/archive  but it is possible to push them directly to another machine using mod_http_cache.  The dialplan entry would look something like this:
`<action application="set" data="record_path=http_cache://http://127.0.0.1:8008/recordings/callrecimport/${domain_name}/archive/${strftime(%Y)}/${strftime(%b)}/${strftime(%d)}" inline="true"/>`

The channel variable that you spotted (pbx_call_recording_url) can be used to replace the http://127.0.0.1:8008 shown in the example above.

**Comment by AdrianFretwell** [comment]
On a default install you should not need to set anything in the dialplan.  You would enable call recording on the extension record.
https://www.djangopbx.com/static/documentation/admin/accounts/extensions.html

**Comment by mrtian** [comment]
Yes,It was set to all in the beginning.

**Comment by mrtian** [comment]
I know what caused the problem, I created the extension only， did not  created the user of the extension. In this case, there is no recording.
