### ISSUE TITLE
Unable to set Call Flow as Destination

### ISSUE THREAD

**Issue by rmakings** [djangopbx/djangopbx#21]
Using the IVR or Call Flow exit destination, the UI does not allow selecting a Call Flow extension as the destination.

You can export/import and manually change the "transfer: nnn XML" , but this does not seem to actually affect anything (probably getting overwritten?).

**Comment by AdrianFretwell** [comment]
I believe this is now fixed, it was a simple typo in the selection of dialplan records by their category.
Commit: https://github.com/djangopbx/djangopbx/commit/a59921261328f6146f25133a7d7f5164cb4f6c27

**Comment by rmakings** [comment]
Yep, that did it!  Thanks so much for the quick resolution.
