### ISSUE TITLE
Provisioning device template UI choice keeps growing

### ISSUE THREAD

**Issue by chris021** [djangopbx/djangopbx#6]
The array is set at the time the class is created, but the function that scans the file system looks to be called multiple times, adding to the list. 
 
<img width="433" alt="image" src="https://github.com/djangopbx/djangopbx/assets/13069808/cf787a85-7482-40d0-b041-75ecb64a8d97">

**Comment by AdrianFretwell** [comment]
Hi Chris,
Thank you for finding this.  The problem was that the template list was not getting re-initialised for each call to get the list.  The following commit fixes this.
https://github.com/djangopbx/djangopbx/commit/90b4dfbe0823091251d15d5744af7a4bca8f45c9
