### ISSUE TITLE
Unable to connect to the FreeSWITCH Event Socket

### ISSUE THREAD

**Issue by wardmundy** [djangopbx/djangopbx#7]
Any idea what's causing this? _systemctl status freeswitch_ shows Freeswitch active.

**Comment by wardmundy** [comment]
/var/log/freeswitch/freeswitch.log is not there. Only files in directory are freeswitch.xml.fsxml  and xml_cdr.

**Comment by AdrianFretwell** [comment]
Without any log files it is difficult to help you.
Will you post the full output of both "systemctl status freeswitch" and "lsb_release -a"

**Comment by wardmundy** [comment]
Domain replaced with xxx.org

systemctl status freeswitch

● freeswitch.service - freeswitch
     Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-02-03 16:26:27 UTC; 22h ago
    Process: 1494 ExecStartPre=/bin/mkdir -p /var/run/freeswitch/ (code=exited, status=0/SUCCESS)
    Process: 1495 ExecStartPre=/bin/chown -R ${USER}:${GROUP} /var/lib/freeswitch /var/log/freeswitch /home/django-pbx/freeswitch /usr/share/freeswitch /var/run/freeswitch (code=exited, status=0/SUCCESS)
    Process: 1496 ExecStart=/usr/bin/freeswitch -u ${USER} -g ${GROUP} -ncwait -conf /home/django-pbx/freeswitch -log /var/log/freeswitch -db /var/lib/freeswitch/db -run /var/run/freeswitch ${DAEMON_OPTS} (code=exited, status=0/SUCCESS)
   Main PID: 1497 (freeswitch)
      Tasks: 10 (limit: 1099)
     Memory: 13.5M
        CPU: 4min 46.091s
     CGroup: /system.slice/freeswitch.service
             └─1497 /usr/bin/freeswitch -u django-pbx -g django-pbx -ncwait -conf /home/django-pbx/freeswitch -log /var/log/freeswitch -db /var/lib/freeswitch/db -run /var/run/freeswitch -nonat

Feb 03 16:26:21 djangopbx.xxx.org systemd[1]: Starting freeswitch.service - freeswitch...
Feb 03 16:26:21 djangopbx.xxx.org freeswitch[1496]: 1497 Backgrounding.
Feb 03 16:26:27 djangopbx.xxx.org freeswitch[1496]: FreeSWITCH[1496] Waiting for background process pid:1497 to be ready.....
Feb 03 16:26:27 djangopbx.xxx.org freeswitch[1496]: FreeSWITCH[1496] Waiting for background process pid:1497 to be ready.....
Feb 03 16:26:27 djangopbx.xxx.org freeswitch[1496]: FreeSWITCH[1496] Waiting for background process pid:1497 to be ready.....
Feb 03 16:26:27 djangopbx.xxx.org freeswitch[1496]: FreeSWITCH[1496] System Ready pid:1497
Feb 03 16:26:27 djangopbx.xxx.org systemd[1]: Started freeswitch.service - freeswitch.

root@djangopbx:~# cd /var/log/freeswitch
root@djangopbx:/var/log/freeswitch# ls
freeswitch.xml.fsxml  xml_cdr

root@djangopbx:/var/log/freeswitch# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by AdrianFretwell** [comment]
Ok, that all looks fine, when you say "Unable to connect to the FreeSWITCH Event Socket" what are you actually doing?

I'm trying to understand if this is an error from the web GUI or when trying to connect with fs_cli or something else.

**Comment by wardmundy** [comment]
In the GUI, choosing Home -> Switch Dashboard produces the FS Event Socket error.
Home -> Dashboard reports Server Error (500)
Status -> FS Log Viewer reports freeswitch.log missing.

**Comment by AdrianFretwell** [comment]
Thankyou all noted.
What happens if you type fs_cli at the command line?

**Comment by wardmundy** [comment]
[ERROR] fs_cli.c:1699 main() Error Connecting []
Usage: fs_cli [-H <host>] [-P <port>] [-p <secret>] [-d <level>] [-x command] [-t <timeout_ms>] [profile]

**Comment by AdrianFretwell** [comment]
OK, your installation of FreeSWITCH is incomplete, you are certainly missing mod_event_socket.so or at the very least it's configuration file.
You are also probably missing mod_logfile.so as well.

Did you build FreeSWITCH from source on this installation?

**Comment by wardmundy** [comment]
Correct. Built from source.

**Comment by wardmundy** [comment]
Starting over. Will use a token this time.

**Comment by AdrianFretwell** [comment]
Ok, I hope you have better luck with the token.
I am just going to do an install building from source to double check the install, I will report back...

**Comment by wardmundy** [comment]
Up and running correctly now using SignalWire personal access token. Thanks.

**Comment by wardmundy** [comment]
Here's what worked for me... 

https://www.voip-info.org/forum/threads/djangopbx-a-new-freeswitch-front-end-gui.27560/#post-175120

**Comment by AdrianFretwell** [comment]
The install script was missing librabbitmq-dev which is required for the current FreeSSWITCH build configuration.  This missing library prevented all modules form building - hence no mod_logfile etc.

The following commit fixes this issue:
https://github.com/djangopbx/djangopbx-install.sh/commit/09465f373cc5533522dfbc23ac044f7917e808d2
