### ISSUE TITLE
Creating Gateways Fail with 500 Error

### ISSUE THREAD

**Issue by wardmundy** [djangopbx/djangopbx#8]
Everything appears up and running but attempting to connect to a provider using the Gateway setup in the Admin Panel always fails with a 500 error and nothing in logs. But the Time of Day and Music on Hold features work great through a registered extension. :-)

**Comment by AdrianFretwell** [comment]
I have been unable to replicate the issue,  I assume you get the 500 error when you click save on the gateway record.
Can you post a screen shot of the gateway admin page just prior to saving it please.

**Comment by AdrianFretwell** [comment]
Also. when you say nothing in the logs, have you also checked ~/pbx/general.log?

**Comment by wardmundy** [comment]
ERROR Internal Server Error: /admin/accounts/gateway/add/

Traceback (most recent call last):

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/core/handlers/exception.py",
line 55, in inner

    response = get_response(request)

               ^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/core/handlers/base.py",
line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py",
line 714, in wrapper

    return self.admin_site.admin_view(view)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py",
line 188, in _view_wrapper

    result = _process_exception(request, e)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py",
line 186, in _view_wrapper

    response = view_func(request, *args, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/views/decorators/cache.py",
line 80, in _view_wrapper

    response = view_func(request, *args, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/sites.py",
line 240, in inner

    return view(request, *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py",
line 1941, in add_view

    return self.changeform_view(request, None, form_url, extra_context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py",
line 48, in _wrapper

    return bound_method(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py",
line 188, in _view_wrapper

    result = _process_exception(request, e)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/utils/decorators.py",
line 186, in _view_wrapper

    response = view_func(request, *args, **kwargs)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py",
line 1802, in changeform_view

    return self._changeform_view(request, object_id, form_url,
extra_context)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/contrib/admin/options.py",
line 1853, in _changeform_view

    self.save_model(request, new_object, form, not add)

  File "/home/django-pbx/pbx/accounts/admin.py", line 426, in save_model

    obj.domain_id = DomainUtils().domain_from_session(request)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/django-pbx/pbx/pbx/commonfunctions.py", line 97, in
domain_from_session

    return Domain.objects.get(name=request.session['domain_name'])

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/db/models/manager.py",
line 87, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File
"/home/django-pbx/envdpbx/lib/python3.11/site-packages/django/db/models/query.py",
line 647, in get

    raise self.model.DoesNotExist(

tenants.models.Domain.DoesNotExist: Domain matching query does not exist.

**Comment by wardmundy** [comment]
Screenshot of Gateway screen setup didn't make it by email. So here is is again...
<img width="514" alt="Screenshot 2024-02-05 at 11 07 11 AM" src="https://github.com/djangopbx/djangopbx/assets/1706147/782abbd7-6dc8-46e1-b094-244ab4725245">

**Comment by AdrianFretwell** [comment]
I can see from your screenshot that you are entering the same kind of information as I have been doing in my tests.
From the log output, I can see that the issue relates to the selected domain in the session:
**return Domain.objects.get(name=request.session['domain_name'])**
The only way that I can replicate this problem is by, selecting a domain and then deleting it or by deleting the default domain for the user and then trying to add a gateway record.

The only way to mitigate this is to add a check to see if the domain recorded in the session, as the selected domain, is still an available domain and if not prevent any action involving the selected domain until a new working domain is selected.

I hope that makes sense.
